apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform.fullname" . }}-api
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" (dict "root" $ "component" "api") | nindent 6 }}
