{{- if not .Values.api.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullname" . }}-api-secrets
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
type: Opaque
stringData:
  DATABASE_URL: {{ tpl .Values.secrets.api.databaseUrl . | quote }}
  REDIS_URL: {{ tpl .Values.secrets.api.redisUrl . | quote }}
  JWT_SECRET: {{ .Values.secrets.api.jwtSecret | quote }}
{{- end }}
