apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-api
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    {{- include "platform.selectorLabels" (dict "root" $ "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.api.service.metricsPort }}
      targetPort: http
