apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform.fullname" . }}-worker-config
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: worker
data:
  {{- range $key, $value := .Values.worker.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
