apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform.fullname" . }}-worker
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: worker
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" (dict "root" $ "component" "worker") | nindent 6 }}
