{{- if not .Values.worker.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullname" . }}-worker-secrets
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: worker
type: Opaque
stringData:
  DATABASE_URL: {{ tpl .Values.secrets.worker.databaseUrl . | quote }}
  REDIS_URL: {{ tpl .Values.secrets.worker.redisUrl . | quote }}
{{- end }}
