version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /apps/worker
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      terraform-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      docker-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /apps/worker
    schedule:
      interval: weekly
    reviewers:
      - zowalska
    groups:
      docker-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
