apiVersion: v1
kind: Namespace
metadata:
  name: platform-staging
  labels:
    app.kubernetes.io/part-of: platform
    environment: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
